env:
  es6: true
  node: true
extends:
  - prettier
  - prettier/@typescript-eslint
ignorePatterns:
  - coverage/**
  - lib/**
overrides:
  - files:
      - "**/*.ts"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: tsconfig.json
      sourceType: module
    rules:
      "@typescript-eslint/adjacent-overload-signatures": error
      "@typescript-eslint/array-type":
        - error
        - default: array-simple
      "@typescript-eslint/ban-types":
        - error
        - types:
            Object:
              message: Avoid using the `Object` type. Did you mean `object`?
            Function:
              message: Avoid using the `Function` type. Prefer a specific function type,
                like `() => void`.
            Boolean:
              message: Avoid using the `Boolean` type. Did you mean `boolean`?
            Number:
              message: Avoid using the `Number` type. Did you mean `number`?
            String:
              message: Avoid using the `String` type. Did you mean `string`?
            Symbol:
              message: Avoid using the `Symbol` type. Did you mean `symbol`?
      "@typescript-eslint/consistent-type-assertions": error
      "@typescript-eslint/consistent-type-definitions": error
      "@typescript-eslint/dot-notation": error
      "@typescript-eslint/explicit-member-accessibility":
        - error
        - accessibility: no-public
      "@typescript-eslint/member-delimiter-style":
        - off
        - multiline:
            delimiter: none
            requireLast: true
          singleline:
            delimiter: semi
            requireLast: false
      "@typescript-eslint/member-ordering": error
      "@typescript-eslint/naming-convention": error
      "@typescript-eslint/no-empty-function": error
      "@typescript-eslint/no-empty-interface": error
      "@typescript-eslint/no-explicit-any": off
      "@typescript-eslint/no-misused-new": error
      "@typescript-eslint/no-namespace": off
      "@typescript-eslint/no-parameter-properties": off
      "@typescript-eslint/no-unused-expressions": error
      "@typescript-eslint/no-use-before-define": off
      "@typescript-eslint/no-var-requires": error
      "@typescript-eslint/prefer-for-of": error
      "@typescript-eslint/prefer-function-type": error
      "@typescript-eslint/prefer-namespace-keyword": error
      "@typescript-eslint/semi":
        - off
        - null
      "@typescript-eslint/triple-slash-reference":
        - error
        - path: always
          types: prefer-import
          lib: always
      "@typescript-eslint/unified-signatures": 0
parser: espree
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
  - jsdoc
rules:
  arrow-body-style: error
  arrow-parens:
    - off
    - always
  brace-style:
    - off
    - off
  complexity: 0
  constructor-super: error
  curly:
    - error
    - multi-line
  eqeqeq:
    - error
    - smart
  guard-for-in: error
  id-blacklist: 0
  id-match: error
  import/order: error
  jsdoc/check-alignment: error
  jsdoc/check-indentation: error
  jsdoc/newline-after-description: error
  max-classes-per-file:
    - error
    - 1
  no-bitwise: error
  no-caller: error
  no-cond-assign: 0
  no-console:
    - error
    - allow:
        - warn
        - dir
        - time
        - timeEnd
        - timeLog
        - trace
        - assert
        - clear
        - count
        - countReset
        - group
        - groupEnd
        - table
        - debug
        - info
        - dirxml
        - error
        - groupCollapsed
        - Console
        - profile
        - profileEnd
        - timeStamp
        - context
  no-debugger: error
  no-empty: error
  no-eval: error
  no-fallthrough: 0
  no-invalid-this: 0
  no-irregular-whitespace: 0
  no-new-wrappers: error
  no-shadow:
    - error
    - hoist: all
  no-throw-literal: error
  no-undef-init: error
  no-underscore-dangle: 0
  no-unsafe-finally: error
  no-unused-labels: error
  no-var: error
  object-shorthand: error
  one-var:
    - error
    - never
  prefer-const: error
  radix: error
  react/jsx-curly-spacing: off
  react/jsx-equals-spacing: off
  react/jsx-wrap-multilines: off
  space-in-parens:
    - off
    - never
  spaced-comment:
    - error
    - always
    - markers:
        - /
  use-isnan: error
  valid-typeof: 0
